### ISSUE TITLE
Not compatible with 2019.1

### ISSUE THREAD

**Issue by pawelkuras** [szymonprz/idea-cheatsh-plugin#21]
Not compatible with 2019.1.

**Comment by szymonprz** [comment]
thanks for info, I will update it as soon as possible :)

**Comment by szymonprz** [comment]
New version of plugin which is now compatible with 2019.1 and even later version of idea was uploaded to plugin repository. It should be available to download within 2 business days

**Comment by pawelkuras** [comment]
thanks.
