### ISSUE TITLE
2019.1.1 ReplaceQuestionWithAnswer fails

### ISSUE THREAD

**Issue by pawelkuras** [szymonprz/idea-cheatsh-plugin#23]
- in 2019.1.1 ReplaceQuestionWithAnswer shortcut fails with:
```
java.lang.NoClassDefFoundError: com/mashape/unirest/http/Unirest
	at pl.szymonprz.cheatsh.plugin.answerclient.CheatshAnswerLoader.answerFor(CheatshAnswerLoader.kt:9)
	at pl.szymonprz.cheatsh.plugin.ui.AbstractAnswerHandler$execute$1.run(AbstractAnswerHandler.kt:29)
.
.
.
```

**Comment by flyingnobita** [comment]
Same here

**Comment by szymonprz** [comment]
Thanks for info, something failed while building new version i think. I will fix it today and new version will be published :)

**Comment by szymonprz** [comment]
New version of plugin was uploaded, again it should be available within two days, please let me know if everything works now :)

**Comment by flyingnobita** [comment]
works now, thanks!
