### ISSUE TITLE
Optionally use selection only

### ISSUE THREAD

**Issue by keyle** [szymonprz/idea-cheatsh-plugin#29]
Thanks for doing this, 

a small suggestion as you indicated welcome, 

_when the user made a selection within the snippet box and press OK, only return the selection to the IDE._

**Comment by szymonprz** [comment]
Hi,
Thanks for you feedback, it's a nice feature request! Definitely possible to implement. Will try to do it as soon as I will have some time

**Comment by szymonprz** [comment]
Hi @keyle sorry for such a delay, but I have great news for you. I've just published new plugin version to marketplace and it's now being verified, soon you will be able to upgrade this plugin and this feature will be available :)
